(defun imprimirDatosBanco()
  (format t "~%")
  (format t "Nit: ~S~%" (Banco-nit ban))
  (format t "Nombre: ~S~%" (Banco-nombre ban))
  (format t "Numero de empleados: ~S~%" (Banco-num_empleados ban))
)

(defun imprimirDatosCliente()
  (format t "ID: ~S~%" (Cliente-id cli))
  (format t "Nombre: ~S~%" (Cliente-nombre cli))
  (format t "Genero: ~S~%" (Cliente-genero cli))
)
