(defun llenarDatosBanco(ban)
   (print "Digite el nit:")
   (setf (Banco-nit ban)(read))
   (print "Digite el nombre:")
   (setf (Banco-nombre ban)(read))
   (print "Digite el numero de empleados:")
   (setf (Banco-num_empleados ban)(read))
)

(defun llenarDatosCliente(cli)
   (print "Digite el id:")
    (setf (Cliente-id cli)(read))
    (print "Digite el nombre:")
    (setf (Cliente-nombre cli)(read))
    (print "Digite el genero:")
    (setf (Cliente-genero cli)(read))
)
