(defun llenarDatosCliente(cli)
   (print "Digite el id:")
    (setf (Cliente-id cli)(read))
    (print "Digite el nombre:")
    (setf (Cliente-nombre cli)(read))
    (print "Digite el genero:")
    (setf (Cliente-genero cli)(read))
)